# Generated by Django 6.0.6 on 2026-07-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=100)),
                ('work_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
